#!/usr/bin/env bash
LABEL="Debian - linux boot-stub"
KERNEL_EFI='\EFI\debian\vmlinuz'
INITRD_EFI='\EFI\debian\initrd.img'

ROOT="$(findmnt -kno UUID /)"
ROOTFS="$(findmnt -kno FSTYPE /)"

ESP="$(findmnt -kno SOURCE /boot/efi | sed s-/dev/--)"
ESP_DISK="$(lsblk /dev/${ESP} -no pkname)"
ESP_PART="$(cat /sys/class/block/${ESP}/partition)"

. /etc/default/efistub-boot

echo "Using partition ${ESP_PART} of ${ESP_DISK} as ESP"

OLD_ENTRY=$(efibootmgr | grep "* ${LABEL}$" | cut -c 5-8)
if test -n "${OLD_ENTRY}"; then
  echo "  deleting boot${OLD_ENTRY}..."
  efibootmgr -B -b $OLD_ENTRY > /dev/null
fi

echo "  creating entry - '${LABEL}'"

efibootmgr -c --disk /dev/${ESP_DISK} --part ${ESP_PART} \
    -L "${LABEL}" -l "${KERNEL_EFI}" \
    -u " root=UUID=${ROOT} ro rootfstype=${ROOTFS} initrd=${INITRD_EFI} ${CMDLINE_LINUX}"\
    > /dev/null
