#!/usr/bin/env bash
LABEL="Debian - linux boot-stub"
KERNEL='\EFI\debian\vmlinuz'
INITRD='\EFI\debian\initrd.img'

ROOT="$(findmnt -kno SOURCE /)"
if test "lvm" != "$(lsblk ${ROOT} -no TYPE)"; then
  ROOT="UUID=$(findmnt -kno UUID /)"
fi
ROOTFS="$(findmnt -kno FSTYPE /)"

echo "Found root: '${ROOT}' (${ROOTFS})"

ESP="$(findmnt -kno SOURCE /boot/efi | sed s-/dev/--)"
ESP_DISK="$(lsblk /dev/${ESP} -no pkname)"
ESP_PART="$(cat /sys/class/block/${ESP}/partition)"

. /etc/default/efistub-boot

echo "Found ESP: '${ESP_DISK}', part ${ESP_PART}"

OLD_ENTRY=$(efibootmgr | grep "* ${LABEL}$" | cut -c 5-8)
if test -n "${OLD_ENTRY}"; then
  echo "  deleting boot${OLD_ENTRY}..."
  efibootmgr -B -b $OLD_ENTRY > /dev/null
fi

echo "  creating '${LABEL}'..."

echo efibootmgr -c --disk /dev/${ESP_DISK} --part ${ESP_PART} \
    -L "${LABEL}" -l "${KERNEL}" \
    -u " root=${ROOT} ro rootfstype=${ROOTFS} initrd=${INITRD} ${CMDLINE_LINUX}"\
    > /dev/null
