#!/bin/sh

KERNEL_VERSION="$(linux-version list | tail -n 1)"
SUFFIX=$(hostname)

. /etc/default/efistub-boot

if [ ! -n "$KERNEL" ]; then
    KERNEL="/boot/efi/EFI/debian/vmlinuz-${SUFFIX}"
fi

if [ "$1" != "$KERNEL_VERSION" ]; then
	echo "efistub-boot: $1 ≠ $KERNEL_VERSION! skipping."
	exit 0
fi

SRC="/boot/vmlinuz-${1}"
if [ -n "$2" ]; then
	SRC="$2"
fi

if [ ! -s "$SRC" ]; then
	echo "efistub-boot: $SRC does not exist!"
	exit 1
fi

if [ -s "$KERNEL" ]; then
	cmp -s "$KERNEL" "$SRC"

	if [ $? -eq 0 ]; then
		echo "efistub-boot: $SRC already installed to ESP. skipping."
		exit 0
	fi
fi

cp "$SRC" "$KERNEL"

if [ $? != "0" ]; then
    echo "copy $SRC to ESP failed!"
    exit 1
fi

echo "efistub-boot: installed $SRC to ESP."
